<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Close &times;</button>
        <span class="h1 modal-title fancy" id="termsModalLabel">Terms &amp; Conditions</span>
      </div>
      <div class="modal-body">
        <p>The Site is provided by Save On, together with its affiliates and subsidiaries (collectively, “SAVE”). The “Site” includes, without limitation: (a) all websites, co-branded Microsites, services, or applications owned or provided by SAVE, and all services offered on or through www.saveon.com or www.saveontravel.com or www.saveongroceries.com, and other services accessible via www.saveon.com or www.saveontravel.com or www.saveongroceries.com (“Services”);</p>
        <p>(b) all software offerings and applications owned or provided by SAVE and/or available on or through www.saveon.com or www.saveontravel.com or www.saveongroceries.com (“Software”);</p> <p>and (c) web pages, data, text, trademarks, logos, images, photographs, graphics, sound, music, user interfaces, visual interfaces, video, and documents including, without limitation, offers and SAVE, marketing materials, press releases, white papers, product data sheets, and other information and content available on or through or submitted on or through www.saveon.com or www.saveontravel.com or www.saveongroceries.com</p>
        <p>(“Content”) including but not limited to the design structure, selection, coordination, expression, “look &amp; feel” and arrangement of such content, contained on the site, controlled or license by or to SAVE. By accessing or using the Site, you agree to comply with and be bound by the following terms and conditions (“Terms of Use”) and the SAVE Privacy Policy. <strong>IF YOU DO NOT AGREE TO THESE TERMS OF USE, PLEASE DO NOT USE THE SITE.</strong></p>
                <hr>
                <br>
                <p><span class="h2 hblock">UPDATES</span></p>
                <p>SAVE may revise these Terms of Use or our Privacy Policy at any time. If SAVE decides to change these Terms of Use, SAVE will post the changes to these Terms of Use and other places SAVE deems appropriate so that you are aware of the change(s). Any changes will be effective upon posting as revised, and your continued use of the Site following the posting will constitute your acceptance of the Terms of Use as revised. SAVE reserves the right, in its sole discretion, to correct any errors or omissions in any portion of the website. <strong>IF YOU DO NOT AGREE TO THE MODIFIED TERMS CONDITIONS OF USE, PLEASE DISCONTINUE USE OF THE SITE.</strong></p>
                <hr>
                <br>
                <p><span class="h2 hblock">PRIVACY</span></p>
                <p>SAVE considers protecting your personal data very important, and has developed a <a href="{{URL::abs('/')}}/privacy">Privacy Policy</a> describing SAVE’s data collection policies and practices, which is incorporated into these Terms of Use by reference as if set forth in its entirety herein.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">CHILDREN</span></p>
                <p>If you are under 13 years of age, then please do not use or access the Site at any time or in any manner, or submit any information to the Site or to SAVE.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">OTHER TERMS</span></p>
                <p>Some areas of the Site may have additional rules, guidelines, license agreements, or other terms and conditions that apply to your access and/or use of that area of the Site and that may be revised from time to time (“Other Terms”). If there is a conflict or inconsistency between these Terms of Use and the Other Terms, the Other Terms shall take precedence with respect to your access and use of that area of the Site.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">USE OF THE SITE</span></p>
                <p>Access to and use of password protected or secure areas of the Site is restricted to authorized users only. You agree that you will not share your password(s), account information, or access to the Site. You are responsible for maintaining the confidentiality of your password(s) and account information, and you are responsible for all activities that occur using your password(s) or account(s) and/or as a result of your use or access to the Site. You agree to notify SAVE immediately of any unauthorized use of your password(s) or account(s). You agree that SAVE will not be liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge. However, you could be held liable for losses incurred by SAVE or another due to someone else using your account or password. You may not use anyone else's account at any time, without the permission of the account holder. </p>

                <p>You agree not to access or use the Site in any manner that may damage, disable, unduly burden, or impair any SAVE networks or systems. You agree not to attempt to gain unauthorized access to any areas of the Site, or any SAVE networks or systems, or to take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or Save On's systems or networks, or any systems or network connected to the Website or to SAVE’s. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person’s use of the Website. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to SAVE on or through the Website or any service offered on or through the Website. You may not use the Website or any Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of SAVE or others. You shall not link this Website to any other site without the expressed written approval of SAVE. You agree not to attempt to interfere with Services provided to any user, host or network, including, without limitation, via means of submitting a virus to the Site, spamming, crashing, or otherwise. Use any robot or “deep-link” or “page-scraping” spider, or any other automated devices, program, algorithm or methodology or any similar or equivalent manual process, to access/acquire, copy or monitor any portion of the website or any content, or in any way reprove or circumvent the navigational structure or presentation of the website or any content to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the web to access or use the Site or any SAVE, notwithstanding features on the website, networks or systems.</p>

                <p>Notwithstanding, you may print or download one copy of the information on this Website solely for your personal non-commercial home use, provided you keep intact all copyright, trademark and other proprietary notices, and you may print or download the coupons provided on this Website. All registered trademark ®, trademarks ™ and service marks that may be used on the coupons featured on this Website to identify the products and services of other companies are the property of their respective owners. SAVE makes no claims to these trademarks &reg;, trademarks&trade; and service marks that identify products and services displayed on coupons featured on this Website.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">ADDITIONAL RESPONSIBLITIES</span></p>
                <p>You agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Site and (b) maintain and promptly update information about yourself to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or SAVE has reasonable to suspicion that such information is untrue, inaccurate, not current or incomplete, or you otherwise have violated these Terms of Use, SAVE has the right to suspend or terminate your account and refuse any or all current or future use of the Site and/or Services (or any portion thereof).</p>
                <hr>
                <br>
                <p><span class="h2 hblock">USE OF SOFTWARE</span></p>
                <p>Your use of Software is subject to these Terms of Use and all agreements including all license agreements and end user agreements that accompany or are included with the Software, and other terms and conditions that apply. In the event that Software is provided on or through the Site and is not licensed for your use you may use the Software subject to all of the following: (a) The Software may be used solely for your personal and noncommercial purposes; (b) You may not attempt to, or authorize any third party to, decompile, reverse engineer or otherwise attempt to gain access to the Software source code; (c) You may not attempt to, or authorize any third party to, disable or circumvent the intended operation of the Software or disclose any such method or means to any third party; (d) The Software may not be modified or altered in any way; and (e) The Software may not be transferred, sublicensed, assigned, copied, or redistributed.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">SERVICES</span></p>
                <p>SAVE may change the Services offered on or through the Site at any time without notice. SAVE makes no representation that the Site is available for use in your location, and a reference to Services within the Site does not imply that the Services will be available to you and/or in your location.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">CONTENT</span></p>
                <p>All Content, including without limitation, any offer or coupon, grocery product, recipe, drug, and health information is provided on or through the Site for informational purposes only, and should NOT be construed to indicate that any such Content is endorsed by SAVE, effective, or safe for your use. Always consult your medical professional regarding any health or medical condition and before using any medical product or any over-the-counter drug. SAVE makes no representation or guarantee or endorsement that the Content is accurate, reliability complete or timely, and reliance on any information opinion, advice, statement or memorandum within the Content or provided on or through the Site is solely at your own risk. SAVE reserves the right at all times to disclose any information as necessary to satisfy any law, regulation or government request, or to edit, refuse to post or to remove any information or materials, in whole or in part, that in SAVE’s sole discretion is objectionable or in violation of these Terms of Use.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">THIRD PARTY CONTENT</span></p>
                <p>The Site provides links to websites and access to content, products and services of third parties, and SAVE makes no representation or guarantee regarding, and accepts no responsibility or liability for, the accuracy, quality, content, nature or reliability of websites and content accessible from the Site, and you bear all risks associated with your access and use of such websites and third party content, products and/or services. Further, links to third party websites and content do not imply endorsement by or affiliation of SAVE with any third party or any third party website, products and/or services.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">INFORMATION</span></p>
                <p>SAVE shall not be liable for any errors or delays in the content, or for any actions taken in reliance thereon. All coupons, offers and promotions on this site are subject to change without notice. SAVE provides you, our visitors, a venue for obtaining the information contained in this Website and has no control over the legality of any coupons or other offers made by other companies features on saveon.com, the ability of any of the other companies to complete the sales in accordance with the offers, or the quality of the good and/or services offers and promotions on this site are subject to change without notice. SAVE provides you, our visitor, a venue for obtaining the information contained in this website and has no control over the legality of any coupons or other offers made by other companies features on saveon.com, the ability of any of the other companies to complete the sales in accordance with the offers, or the quality of the goods and/or services offered by the other companies. SAVE has no control over whether the other companies will honor the offers and coupons shown on this Website and does not guarantee the assurance or completeness of the information contained on this website. In the event you have a dispute with another company in any way relating to this Website or the use of information from this Website, you agree to waive and release SAVE from any and all claims, demands, actions, damages (actual and consequential), losses, costs or expenses of every kind and nature, know and unknown, disclosed and undisclosed relating to the dispute.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">FEEDBACK</span></p>
                <p>All comments or materials submitted by you to SAVE through the Site, including without limitation, feedback, testimonials, images, reviews, questions, comments, ideas, or suggestions (collectively, “Feedback”) shall be received and treated by SAVE on a non-confidential and unrestricted basis. Further, SAVE shall be free to use, copy, display, perform, distribute, adapt, and promote, in any medium now known or later developed, without compensation to you, the Feedback along with all ideas, concepts, know-how, techniques or methodologies contained in such Feedback, for any purpose whatsoever, including without limitation, developing, marketing and selling products and/or services incorporating such Feedback. You agree that in submitting Feedback, it will not violate these Terms of Use or any right of any third party, including without limitation, any confidentiality, copyright, trademark, privacy or other personal or intellectual property or proprietary rights, and will not cause injury to any person or entity. You further agree that no Feedback you submit will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain viruses, commercial solicitations, or any form of “spam”.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">OWNERSHIP</span></p>
                <p>All right, title and interest in and to the Site and Content are and shall remain the intellectual property and copyrighted works of SAVE and/or its licensors, and all rights not expressly granted to you with respect to the Site and Content shall be expressly reserved. You may not use or frame any SAVE name, trademark, logo or other proprietary materials, including images posted on the Site, the Content of any text or the design of any page, or form contained on a page, without SAVE’ express prior written consent. Except as stated in these Terms of Use, no Content may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means, including without limitation, electronic, mechanical, photocopying, recording or otherwise without the prior written consent of SAVE or the respective owner.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">DISCLAIMER</span></p>
                <p>EXCEPT WHERE EXPRESSLY PROVIDED OTHERWISE, THE SITE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. SAVE EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. FURTHER, SAVE MAKES NO WARRANTY THAT: (A) THE SITE, SERVICES, SOFTWARE, OR CONTENT WILL MEET YOUR REQUIREMENTS; (B) THE SITE WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; (C) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SITE, SERVICES, SOFTWARE, OR ANY CONTENT PROVIDED ON OR THROUGH THE SITE WILL BE ACCURATE, TIMELY, OR RELIABLE; OR (D) THE QUALITY OF ANY SERVICES OR CONTENT OBTAINED BY YOU ON OR THROUGH THE SITE WILL MEET YOUR EXPECTATIONS. ANY SERVICES, SOFTWARE OR CONTENT ACCESSED, USED, DOWNLOADED OR OTHERWISE OBTAINED ON OR THROUGH THE SITE IS USED BY YOU AT YOUR OWN RISK. SAVE SHALL HAVE NO RESPONSIBILITY OR LIABILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM USE OF THE SITE, SOFTWARE, OR CONTENT.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">LIMITATION OF LIABILITY</span></p>
                <p>YOU ASSUME COMPLETE RESPONSIBILITY AND RISK FOR YOUR USE OF THE WEBSITE. IN NO EVENT SHALL SAVE AND ITS LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA OR USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, ARISING FROM YOUR ACCESS TO, OR USE OF, OR INABILITY TO USE THE SITE OR ANY SERVICES, SOFTWARE, OR CONTENT PROVIDED ON OR THROUGH THE SITE, EVEN IF SAVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES. NOTWITHSTANDING THE FOREGOING, THE TOTAL LIABILITY OF SAVE AND ITS LICENSORS, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE), PRODUCT LIABILITY, STRICT LIABILITY OR ANY OTHER THEORY, ASSOCIATED WITH ANY CLAIM ARISING OUT OF OR RELATING TO USE OR ACCESS TO THE SITE FOR ANY REASON WHATSOEVER SHALL BE LIMITED TO THE COST OF ACCESSING THE SITE, IF ANY.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">LIMITATIONS</span></p>
                <p>SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OR EXCLUSION OF CERTAIN WARRANTIES OR THE DISCLAIMER OR EXCLUSION OF CERTAIN LIABILITIES. TO THE EXTENT THAT THEY ARE HELD TO BE LEGALLY INVALID, DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS SET FORTH IN THESE TERMS OF USE DO NOT APPLY; HOWEVER, ALL OTHER TERMS AND CONDITIONS SHALL APPLY AND REMAIN IN FULL FORCE AND EFFECT.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">INDEMNITY</span></p>
                <p>You agree to defend, indemnify and hold SAVE and its officers, directors, employees, agents and affiliates harmless from any and all claims, proceedings, damages, injuries, liabilities, losses, costs and expenses (including reasonable attorneys' fees and litigation expenses), arising out of or relating to your use of the Site, Services, Software or Content or your violation of these Terms of Use.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">TERMINATION</span></p>
                <p>SAVE has the right, but not the obligation, to monitor any activity on the Site. SAVE may disclose information from the Site to any third party including law enforcement agencies to protect its rights and property in response to legal process, or in a good faith belief that disclosure is justified or required, or in an emergency situation. SAVE may investigate any reported violation of its policies and complaints, and take any appropriate action it deems appropriate at any time, including without limitation, suspension or termination of access and/or use of the Site, or any applicable Services, Software or Content. In addition, SAVE may, in its sole discretion and at any time, discontinue providing or limit access to the Site or any areas of the Site.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">GOVERNING LAW</span></p>
                <p>These Terms of Use shall be governed by and construed in accordance with the laws of the State of Michigan, without resort to its conflict of law principles. Regardless of where you access or use the Site, you agree that any action at law or in equity arising out of or relating to these Terms of Use shall be filed and adjudicated only in the federal or state courts located in Oakland County, Michigan, and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction and venue of such courts over any suit, action, or proceedings arising out of these Terms of Use.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">COMPLIANCE WITH LAWS</span></p>
                <p>You agree not to use the Site, Services, Software, or Content provided on or through the Site for any purpose that is unlawful or prohibited by these Terms of Use. Further, you agree not to access, download, use or export the Site, Services, Software, or Content provided on or through the Site, in violation of U.S. export laws or regulations, or in violation of any other applicable laws, rules or regulations. You agree to comply with all export laws and restrictions and regulations of any United States or foreign agency or authority, and not to directly or indirectly provide or otherwise make available the Site, Services, Software, or Content in violation of any such restrictions, laws, rules or regulations, or without all necessary approvals.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">COMPLETE AGREEMENT</span></p>
                <p>They contain the entire understanding and agreement of the parties relating to the subject matter. In the event that any provision of these terms and conditions is determined to be invalid, unenforceable or otherwise illegal, such provision shall be deemed severed and the remainder of the terms and conditions shall remain in full force and effect. No term or condition shall be deemed waived, and no breach shall be deemed excused, unless such waiver is in writing and is executed by the party against who such waiver or excuse is claimed.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">GENERAL</span></p>
                <p>These Terms of Use and any other electronic policies and guidelines referenced and thereby incorporated herein will be deemed to be in compliance with applicable statutory, contractual, and other legal requirements for writing and be legally enforceable as a signed writing as against the parties, and deemed an “original” and “in writing” when printed from electronic records established and maintained in the ordinary course of business. If any portion of these Terms of Use is held invalid, you agree that such invalidity will not affect the validity of the remaining portions of these Terms of Use. No waiver by SAVE of any breach or default of these Terms of Use will constitute a continuing waiver of such breach or default or be deemed to be a waiver of any preceding or subsequent breach or default. These Terms of Use represent the complete agreement between SAVE and you regarding the subject matter set forth herein and supersedes all prior agreements and representations between SAVE and you.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">COPYRIGHT &amp; TRADEMARK</span></p>
                <p>Copyright &copy; 2014 Save On. All Rights Reserved. The Save On logo is a registered trademark of Save On Everything. All other trademarks, logos and service marks are the property of Save On or their respective owners.</p>
                <hr>
                <br>
                <p><span class="h2 hblock">CONTACT INFORMATION</span></p>
                <p>If you have any questions regarding these Terms of Use, please contact Save On at contact us or by mail at:
                    Save On<br>
                    1000 West Maple<br>
                    Troy, MI 48084<br>
                    Attn: Legal Dept.
                    <p>

                <p><img src="/img/terms-updated.gif" alt="Last updated: April 11, 2013"></p>
      </div>
    </div>
</div>
